### ISSUE TITLE
[Question] Comparison with BEP42 for BitTorrent DHT?

### ISSUE THREAD

**Issue by zanetu** [kadtools/kad-spartacus#3]
It appears to me that [BEP42 for BitTorrent DHT](http://www.bittorrent.org/beps/bep_0042.html), DHT Security extension, is also aimed to thwart Sybil attack. I wonder if kad-spartacus is superior in terms of robustness, performance, etc. and if it can solve all problems that BEP42 is intended to address. Did you ever make a comparison (where applicable)? Is kad-spartacus applicable to kad-webrtc (since there is only a UDP example in your README)?

**Comment by gordonwritescode** [comment]
@zanetu I have not reviewed BEP42, but will take some time to do so and get back to you with an answer of how it compares to what is implemented here.

Regarding kad-webrtc, this should function as expected, you'd change the example to:

```js
var kademlia = require('kad');
var WebRTC = require('kad-webrtc');
var spartacus = require('kad-spartacus');

// Import your private EC key or create a new key pair
var keypair = new spartacus.KeyPair(privkey);

// Setup your Contact for Spartacus
var Contact = spartacus.ContactDecorator(WebRTC.Contact);

// Create your transport with a SpartacusContact
var transport = WebRTC(Contact({
  address: '127.0.0.1',
  port: 1337,
  pubkey: keypair.getPublicKey()
}));

// Sign your messages
transport.before('serialize', spartacus.hooks.sign(keypair));

// Verify received messages
transport.before('receive', spartacus.hooks.verify(keypair));
```

**Comment by zanetu** [comment]
OK. Take your time. 

As a side note, I found [a webpage](http://xlattice.sourceforge.net/components/protocol/kademlia/specs.html) that contains identical comments as your README: 
> A Sybil variation is the Spartacus attack, where an attacker joins the network claiming to have the same nodeID as another member. As specified, Kademlia has no defense. In particular, a long-lived node can always steal a short-lived node's nodeID.

Interestingly, that webpage also mentions the approach that BEP42 appears to have adopted: 
> A weaker solution would be to require that nodeIDs be derived from the node's network address or some other quasi-unique value.

**Comment by gordonwritescode** [comment]
Yep, I used that technical specification when I first started working on kad and the note in the README is lifted directly from that page. 

I wanted to implement a solution that was better than the mentioned "weaker" solution but didn't rely on a centralized service for issuing nodeIDs. ECDSA seemed like a good fit. The best an attacker could do in order to control a section of the network, would be to generate enough EC keys whose public key hash are sufficiently close to one another. 

This attack is certainly plausible, but it is computationally expensive to the degree that it would likely be economically infeasible to be able to any real damage to the network. (Someone with a PhD should probably confirm that).

**Comment by omphalos** [comment]
How long does it take to generate an ECDSA signature?

**Comment by gordonwritescode** [comment]
@omphalos depends on the message size and the implementation and I do not have a benchmark on hand, but this module just signs the message ID and a nonce and uses [elliptic](https://github.com/indutny/elliptic/blob/master/README.md), so let's go with *fast*. :)

**Comment by zanetu** [comment]
@gordonwritescode 

That webpage seems to be related to [this project](https://github.com/jddixon/xlattice) but it appears to have drawn little attention on GitHub. 

I know that ECDSA is hard to break. Yet I am curious if your approach outperforms BEP42 in every aspect (e.g. memory usage). Put another way, I am concerned with why BitTorrent developers did not adopt an approach (e.g. the public-key approach you adopted) other than the current network address based scheme. (Of course it could just be the case that they were too lazy to explore other possibilities. lol ) Sure you are not in a position to answer that question on behalf of them but it would not hurt to look at that alternative in the first place. If you are confident that your approach is better than BEP42 in every aspect, we can probably ask BitTorrent developers to incorporate your approach into BEP42. (Of course it depends on whether you are willing to do so. )

Another reason I raise this question is that ECDSA [has been dragged](https://nakedsecurity.sophos.com/2013/08/12/android-random-number-flaw-implicated-in-bitcoin-thefts/) [through the mud](http://www.engadget.com/2010/12/29/hackers-obtain-ps3-private-cryptography-key-due-to-epic-programm/) in recent years. Although the vulnerabilities were not inherent in ECDSA itself, they suggested that ECDSA applications could be vulnerable if improperly implemented. And they could also constitute an incentive to use RSA over ECDSA. (Huge difference in [verification speed](http://web.archive.org/web/20160215094845/http://cryptopp.com/benchmarks.html) might be another. )

PS I'm no cryptography expert so I can't guarantee RSA would be more suitable for Kademlia than ECDSA.

**Comment by omphalos** [comment]
I think the solution currently implemented in kad-spartacus falls under the category of "crypto puzzle" described in S/Kademlia's [paper](http://www.tm.uka.de/doc/SKademlia_2007.pdf).  If key generation is fast then to me it sounds like it might be possible to keep generating keys until the attacker is arbitrarily close to the desired key.  I think crypto puzzles in this sense are supposed to be resource intensive and time consuming so that they are a deterrent to attackers.  I think the choice of IP-based node IDs in BEP42 is because it makes it harder (though not impossible) to mount this kind of attack.

If we were to do something like IPv6-based node IDs in kad-webrtc, this would be very tricky, because nodes can have multiple IPv6 addresses.  The easy solution of just hashing all these IPv6 addresses couldn't work, I think, because a node could add a fake IP address to this range to create a node ID.  It may be possible to validate the address that WebRTC uses for actually connect although that would involve delving into the internals of the ICE description messages that WebRTC passes around, and it might not be possible at all.  Another concern is that I'm not sure if IPv6 is as resistant to this kind of attack as IPv4.

While we're on this topic, another mitigation put into place by S/Kademlia is lookups over disjoint paths.  When I search for a particular key value, I run N lookups, never traversing any of the same nodes during any of the lookups.  The S/Kademlia authors show that this makes it a lot harder to mount these kinds of attacks, assuming node IDs are hard to come by.

**Comment by zanetu** [comment]
@omphalos 

Um... prospective support for IPv6 looks like a sound reason for not using the IP-based scheme. Yet it remains to be seen if ECDSA is the best choice here. (Is there any project that is already using kad-spartacus in production? ) Sure there are other schemes out there to be chosen from (e.g. the disjoint-path scheme in S/Kademlia), but lots of experiments (and hence comparisons) have to be done in order to verify any one of them is a worthy winner. 

Anyway, thanks for the input. I figure I need more time to think it over. Yet I hope you guys will, if possible, come up with some strong argument (preferably with convincing experimental results) showing that your implementation of kad-spartacus is more suitable for Kademlia than existing alternatives, and add it to kad-spartacus README. Of course it's perfectly fine if you don't, but if you do, potential users can be more assured of capability of kad-spartacus before trying it out.
